routes/web.php
<?php

use App\Models\Advertisement;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\OpinionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\AdvertisementController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\User\ShowUserController;
use App\Http\Controllers\UsersAdvertismentController;
use App\Http\Controllers\User\AvailabilityController;
use App\Http\Controllers\User\UserEditProfileController;
use App\Http\Controllers\User\UserEditResetPasswordController;

Auth::routes(['verify' => true]);

Route::post('/logout', [LogoutController::class, 'store'])->name('logout');



Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'store']);


Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'store']);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [App\Http\Controllers\HomePageController::class, 'index'])->name('homePage');
Route::post('/{advert}', [App\Http\Controllers\HomePageController::class, 'singleAdvert'])->name('singleAdvert');

Route::get('/advertisement/add', [AdvertisementController::class, 'add'])->middleware('auth')->name('add_advert');
Route::post('/advertisement/add', [AdvertisementController::class, 'store'])->middleware('auth');

Route::get('/advertisement/show', [AdvertisementController::class, 'show'])->middleware('auth')->name('show_advert');
Route::get('/advertisement/getvoivodeships/{id}', [AdvertisementController::class, 'getVoivodeships'])->middleware('auth');
Route::get('/advertisement/getcities/{id}', [AdvertisementController::class, 'getCities'])->middleware('auth');
Route::get('/advertisement/getdistricts/{id}', [AdvertisementController::class, 'getDistricts'])->middleware('auth');
Route::delete('/advertisement/show/{advert}', [AdvertisementController::class, 'delete'])->middleware('auth')->name('delete_advert');
Route::get('/advertisement/{advert}', [AdvertisementController::class, 'showSingle'])->name('showSingle');
Route::get('/advertisement/edit/{advert}', [AdvertisementController::class, 'editShow'])->middleware('auth')->name('edit_advert');
Route::post('/advertisement/edit/{advert}', [AdvertisementController::class, 'editSave'])->middleware('auth');
Route::post('/advertisement/accept/{advert}', [AdvertisementController::class, 'addApplication'])->middleware('auth')->name('addApplication');
Route::get('/advertisements/showApplications', [AdvertisementController::class, 'showApplications'])->middleware('auth')->name('showApplications');
Route::post('/advertisements/accept', [AdvertisementController::class, 'acceptUser'])->middleware('auth')->name('acceptUser');
//show another user profile
Route::get('/profile/{user}', [ShowUserController::class, 'index'])->middleware('auth')->name('showUser');
Route::delete('/profile/{user}', [ShowUserController::class, 'destroy'])->name('showUser.destroy');
//User opinions
Route::get('/profile/{user}/opinions', [OpinionController::class, 'index'])->middleware('auth')->name('userOpinions');
Route::post('/profile/{user}/opinions', [OpinionController::class, 'addOpinion'])->middleware('auth')->name('addOpinion');
Route::put('/profile/editOpinion/{opinion}', [OpinionController::class, 'editOpinion'])->middleware('auth')->name('editOpinion');
Route::delete('profile/deleteOpinion/{opinion}', [OpinionController::class, 'deleteOpinion'])->middleware('auth')->name('deleteOpinion');

//editing user profile
Route::get('/user/edit', [App\Http\Controllers\User\UserEditProfileController::class, 'index'])->name('userEdit');
Route::delete('/user/edit', [App\Http\Controllers\User\UserEditProfileController::class, 'destroy'])->name('userEdit');
Route::post('/user/edit', [UserEditProfileController::class, 'resetPswd'])->name('reset_pswd');

Route::get('/user/edit/description', [App\Http\Controllers\User\UserEditProfileController::class, 'showDescriptionBlade'])->name('showDescriptionBlade');
Route::post('/user/edit/description', [UserEditProfileController::class, 'storeAbout'])->name('addAbout');

Route::get('/user/edit/nickname', [App\Http\Controllers\User\UserEditProfileController::class, 'showNicknameBlade'])->name('showNicknameBlade');
Route::post('/user/edit/nickname', [UserEditProfileController::class, 'storeNickname'])->name('addNickname');

Route::get('/user/edit/accountType', [App\Http\Controllers\User\UserEditProfileController::class, 'showAccountTypeBlade'])->name('showAccountTypeBlade');
Route::post('/user/edit/accountType', [UserEditProfileController::class, 'storeAccountType'])->name('storeAccountType');

Route::get('/user/edit/photo', [App\Http\Controllers\User\UserEditProfileController::class, 'showPhotoBlade'])->name('showPhotoBlade');
Route::post('/user/edit/photo', [UserEditProfileController::class, 'storePhoto'])->name('storePhoto');

//Messages
Route::get('/profile/{user}/messages', [MessageController::class, 'index'])->middleware('auth')->name('messageList');
Route::post('/profile/{user}/messages', [MessageController::class, 'newMessage'])->middleware('auth')->name('newMessage');
Route::get('/messages/getuser/{id}', [MessageController::class, 'getUser'])->middleware('auth');
Route::post('/messages/markread/{id}', [MessageController::class, 'markRead'])->middleware('auth');
Route::get('/messages/badges', [MessageController::class, 'countBadges'])->middleware('auth');


//Administator
Route::prefix('admin')->name('admin.')->middleware('admin')->group(function (){
    Route::resource('/users', UserController::class);
    
});

Route::post('admin/users/{user}/block', [UserController::class, 'block'])->middleware('admin')->name('admin.users.block');
Route::put('admin/users/{user}/unblock', [UserController::class, 'unblock'])->middleware('admin')->name('admin.users.unblock');
Route::put('admin/users/{user}/makeadmin', [UserController::class, 'makeadmin'])->middleware('admin')->name('admin.users.makeadmin');

//Calendar
Route::get('/calendar', [App\Http\Controllers\UsersAdvertisementsController::class, 'index'])->middleware('auth')->name('calendar');
Route::get('/calendarsend', [App\Http\Controllers\UsersAdvertisementsController::class, 'send'])->middleware('auth')->name('calendarsend');
//Search
Route::get('/search', [App\Http\Controllers\SearchController::class, 'index'])->name('search');
//Availability
Route::prefix('availability')->name('availability.')->middleware('auth')->group(function (){
    Route::resource('/availability', AvailabilityController::class);
    
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('admin.users.index', [
            'users' => User::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:128',  
            'surname' => 'required|max:128', 
            'email' => 'required|email', 
            'password' => 'required|max:128|min:8',
            'id_account_type' => 'required',
            'nickname' => 'required|max:15'
        ]);

        $user =  User::create([
            'name' => $request -> name,
            'surname' => $request -> surname,
            'email' => $request -> email,
            'nickname' => $request -> nickname,
            'password'=> Hash::make($request -> password),
            'id_account_type' => $request -> id_account_type,
            
        ]);

        return redirect()->route('admin.users.index')->with('success', "Użytkownik został pomyślnie utworzony!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        

        return view('admin.users.edit', [
            'user' => User::find($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $this->validate($request, [
            'name' => 'required|max:128',  
            'surname' => 'required|max:128', 
            'email' => 'required|email', 
            'id_account_type' => 'required',
            'nickname' => 'required|max:15',
            'about' => 'max:5000'
        ]);

        $user->name = $request->name;
        $user->surname = $request->surname;
        $user->email = $request->email;
        $user->id_account_type = $request->id_account_type;
        $user->nickname = $request->nickname;
        $user->about = $request->about;


        $user->save();

        return back()->with('success', 'Użytkownik wyedytowany pomyślnie');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {
        $user = User::find($id);

        foreach ($user->sendMessages as $key => $value) {
            $value->from_id_user = 1;
            $value->save();
        }
        foreach ($user->receivedMessages as $key => $value) {
            $value->to_id_user = 1;
            $value->save();
        }

        
         User::destroy($id);
         return back()->with('success', 'Użytkownik został usunięty');
    }

    /**
     * 
     * Block the specified user 
     * '0' means unblocked user
     * '1' means blocked user
     * @param int $id
     */



    public function block($id)
    {
        $user = User::find($id);

       $user->is_blocked = '1';
       $user->save();
 
       return back()->with('success', "Użytkownik pomyślnie zablokowany!");

    }

      /**
     * Unblock the specified user 
     * '0' means unblocked user
     * '1' means blocked user
     * @param int $id
     */

    public function unblock($id)
    {
       
        $user = User::find($id);
            
       $user->is_blocked = '0';
       $user->save();

      
      return back()->with('success', "Użytkownik pomyślnie odblokowany!");

    }

    public function makeAdmin($id)
    {
        $user = User::find($id);

        $user->id_account_type = '3';
        $user->save();

        return back()->with('success', "Użytkownik pomyślnie mianowany administratorem!");
    }
}

app/Http/Controllers/User/AvailabilityController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Availability;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AvailabilityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user()->id;
        $monday = Availability::where('day', '1')->where('id_user', $user)->first();
        $tuesday = Availability::where('day', '2')->where('id_user', $user)->first();
        $wednesday = Availability::where('day', '3')->where('id_user', $user)->first();
        $thursday = Availability::where('day', '4')->where('id_user', $user)->first();
        $friday = Availability::where('day', '5')->where('id_user', $user)->first();
        $saturday = Availability::where('day', '6')->where('id_user', $user)->first();
        $sunday = Availability::where('day', '7')->where('id_user', $user)->first();


        return view('User.Availability.index', [
            'monday' => $monday,
            'tuesday' => $tuesday,
            'wednesday' => $wednesday,
            'thursday' => $thursday,
            'friday' => $friday,
            'saturday' => $saturday,
            'sunday' => $sunday,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($day)
    {
        $when = $day;
        $user = Auth::user()->id;

        return view('User.Availability.edit', [
            'day' => $day,
            'user' =>$user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $day)
    {
        $id = Auth::user()->id;
        $available = Availability::where('day', $day)->where('id_user', $id)->first();

        $this->validate($request, [
            'start_time' => 'required',  
            'stop_time' => 'required|after:start_time',
        ]);
    

        if($available == null) {
            Availability::create([
                'start_time' => $request -> start_time,
                'stop_time' => $request -> stop_time,
                'day' => $day,
                'id_user' => $id,
                
            ]);
        }

        else {
            $available->update([
                'start_time' => $request -> start_time,
                'stop_time' => $request -> stop_time,
               
            ]);
        }

        return redirect()->route('availability.availability.index')
            ->with('success', 'Pomyślnie zaktualizowano dostępność!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/ShowUserController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Models\Opinion;
use Illuminate\Support\Facades\Auth;

class ShowUserController extends Controller
{
    public function index(User $user)
    {
        $opinionAvailable = 0;
        $blocked = $user->is_blocked;

        if(auth()->check() && auth()->user()->id_account_type == 1)
        {
            $applications = auth()->user()->myApplications;
            
            foreach ($applications as $key => $application) 
            {
                if(($application->id_user == $user->id) && ($application->pivot->accepted == 1) && ($application->pivot->time_to < now()))
                {
                    $opinionAvailable = 1;
                }
            }
        }
        elseif(auth()->check() && auth()->user()->id_account_type == 2)
        {
            if(DB::table('users_advertisements')->where([['id_user', $user->id], ['accepted', 1], ['time_to', '<', now()]])->count() > 0)
            {
                $opinionAvailable = 1;
            }
        }
   
        $user = User::select('id' ,'name', 'surname', 'nickname', 'reputation', 'photo', 'about', 'is_blocked', 'id_account_type')
                        ->where('id', $user->id)->get();
        
        $opinions = Opinion::where('to_id_user', $user[0]->id)->paginate(4);

        return view('User.showUser', [
            'user' => $user[0],
            'opinionAvailable' => $opinionAvailable,
            'opinions' => $opinions,
            'blocked' => $blocked
        ]);
    }


    public function destroy($id)
    {
        $user = User::find($id);

        foreach ($user->sendMessages as $key => $value) {
            $value->from_id_user = 1;
            $value->save();
        }
        //$user->receivedMessages()->delete();
        foreach ($user->receivedMessages as $key => $value) {
            $value->to_id_user = 1;
            $value->save();
        }

        
         User::destroy($id);
         return redirect()->route('homePage')->with('status', 'Użytkownik został usunięty');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">


            <div class="card">
                <div class="card-header text-center">{{ __('Formularz tworzenia nowego użytkownika') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.users.store') }}">
                        @csrf

                        <div class="form-group row p-2">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Imię') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') alert alert-danger is-invalid @enderror" name="name" value="{{ old('name') }}"  autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback alert alert-warning " role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row p-2">
                            <label for="surname" class="col-md-4 col-form-label text-md-right">{{ __('Nazwisko') }}</label>

                            <div class="col-md-6">
                                <input id="surname" type="text" class="form-control @error('surname') alert alert-danger is-invalid @enderror" name="surname" value="{{ old('surname') }}"  autocomplete="surname" autofocus>

                                @error('surname')
                                    <span class="invalid-feedback alert alert-warning" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row p-2">
                            <label for="nickname" class="col-md-4 col-form-label text-md-right">{{ __('Nick') }}</label>

                            <div class="col-md-6">
                                <input id="nickname" type="text" class="form-control @error('nickname') alert alert-danger is-invalid @enderror" name="nickname" value="{{ old('nickname') }}"  autocomplete="surname" autofocus>

                                @error('nickname')
                                    <span class="invalid-feedback alert alert-warning" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row p-2">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Adres e-mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') alert alert-danger is-invalid @enderror" name="email" value="{{ old('email') }}"  autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback alert alert-warning" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row p-2">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Hasło') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') alert alert-danger is-invalid @enderror" name="password"  autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback alert alert-warning" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
         
                        <div class="form-group row p-2 ">
                            
                            <label class=" col-md-4 col-form-label text-md-right " for="id_account_type">{{ __('Typ konta') }}</label>
                            
                            <div class="col-md-6"> 
                                <select class=" required custom-select form-control" id="id_account_type" value="{{ old('id_account_type') }}" name="id_account_type"  autocomplete="id_account_type" >
                                    <option value="1">{{ __('Opiekun') }}</option>
                                    <option value="2">{{ __('Zwykły użytkownik') }}</option>
                                    <option value="3">{{ __('Administrator') }}</option>
                                </select>
                            </div>
                        </div>
                      

                        <div class="form-group row p-2">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    {{ __('Utwórz użytkownika') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-8">

            @if (session('success'))
            <div class="text-center alert alert-success ">
                {{ session('success') }}    
               
            </div>
            @endif

            <div class="card">
                <div class="card-header text-center">{{ __('Formularz edycji użytkownika użytkownika') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.users.update', $user->id) }}">
                        @method('PATCH')
                        @csrf

                        <div class="form-group row p-2">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Imię') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') alert alert-danger is-invalid @enderror" name="name" value="{{ $user->name }}"  autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback alert alert-warning " role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row p-2">
                            <label for="surname" class="col-md-4 col-form-label text-md-right">{{ __('Nazwisko') }}</label>

                            <div class="col-md-6">
                                <input id="surname" type="text" class="form-control @error('surname') alert alert-danger is-invalid @enderror" name="surname" value="{{ $user->surname }}"  autocomplete="surname" autofocus>

                                @error('surname')
                                    <span class="invalid-feedback alert alert-warning" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row p-2">
                            <label for="nickname" class="col-md-4 col-form-label text-md-right">{{ __('Nick') }}</label>

                            <div class="col-md-6">
                                <input id="nickname" type="text" class="form-control @error('nickname') alert alert-danger is-invalid @enderror" name="nickname" value="{{ $user->nickname }}"  autocomplete="surname" autofocus>

                                @error('nickname')
                                    <span class="invalid-feedback alert alert-warning" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row p-2">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Adres e-mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') alert alert-danger is-invalid @enderror" name="email" value="{{ $user->email }}"  autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback alert alert-warning" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row p-2 ">
                            
                            <label class=" col-md-4 col-form-label text-md-right " for="id_account_type">{{ __('Typ konta') }}</label>
                            
                            <div class="col-md-6"> 
                                <select class=" required custom-select form-control" id="id_account_type" name="id_account_type"  autocomplete="id_account_type" >
                                    <option value="1" @if($user->id_account_type == '1') selected @endif>{{ __('Opiekun') }}</option>
                                    <option value="2" @if($user->id_account_type == '2') selected @endif>{{ __('Zwykły użytkownik') }}</option>
                                    <option value="3">{{ __('Administrator') }}</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row p-2 ">
                            
                            <label class=" col-md-4 col-form-label text-md-right " for="about">{{ __('Opis konta') }}</label>
                            
                            <div class="col-md-6"> 
                                <textarea id="about" type="text" class="form-control @error('about')
                                alert alert-danger is-invalid
                                @enderror " name="about"  autofocus>{{ $user->about }}</textarea>        
                            </div>
                        </div>

                        
                      

                        <div class="form-group row p-2">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    {{ __('Zapisz zmiany') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection