routes/web.php
<?php

use App\Models\Advertisement;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\OpinionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\AdvertisementController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\User\ShowUserController;
use App\Http\Controllers\UsersAdvertismentController;
use App\Http\Controllers\User\AvailabilityController;
use App\Http\Controllers\User\UserEditProfileController;
use App\Http\Controllers\User\UserEditResetPasswordController;

Auth::routes(['verify' => true]);

Route::post('/logout', [LogoutController::class, 'store'])->name('logout');



Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'store']);


Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'store']);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [App\Http\Controllers\HomePageController::class, 'index'])->name('homePage');
Route::post('/{advert}', [App\Http\Controllers\HomePageController::class, 'singleAdvert'])->name('singleAdvert');

Route::get('/advertisement/add', [AdvertisementController::class, 'add'])->middleware('auth')->name('add_advert');
Route::post('/advertisement/add', [AdvertisementController::class, 'store'])->middleware('auth');

Route::get('/advertisement/show', [AdvertisementController::class, 'show'])->middleware('auth')->name('show_advert');
Route::get('/advertisement/getvoivodeships/{id}', [AdvertisementController::class, 'getVoivodeships'])->middleware('auth');
Route::get('/advertisement/getcities/{id}', [AdvertisementController::class, 'getCities'])->middleware('auth');
Route::get('/advertisement/getdistricts/{id}', [AdvertisementController::class, 'getDistricts'])->middleware('auth');
Route::delete('/advertisement/show/{advert}', [AdvertisementController::class, 'delete'])->middleware('auth')->name('delete_advert');
Route::get('/advertisement/{advert}', [AdvertisementController::class, 'showSingle'])->name('showSingle');
Route::get('/advertisement/edit/{advert}', [AdvertisementController::class, 'editShow'])->middleware('auth')->name('edit_advert');
Route::post('/advertisement/edit/{advert}', [AdvertisementController::class, 'editSave'])->middleware('auth');
Route::post('/advertisement/accept/{advert}', [AdvertisementController::class, 'addApplication'])->middleware('auth')->name('addApplication');
Route::get('/advertisements/showApplications', [AdvertisementController::class, 'showApplications'])->middleware('auth')->name('showApplications');
Route::post('/advertisements/accept', [AdvertisementController::class, 'acceptUser'])->middleware('auth')->name('acceptUser');
//show another user profile
Route::get('/profile/{user}', [ShowUserController::class, 'index'])->middleware('auth')->name('showUser');
Route::delete('/profile/{user}', [ShowUserController::class, 'destroy'])->name('showUser.destroy');
//User opinions
Route::get('/profile/{user}/opinions', [OpinionController::class, 'index'])->middleware('auth')->name('userOpinions');
Route::post('/profile/{user}/opinions', [OpinionController::class, 'addOpinion'])->middleware('auth')->name('addOpinion');
Route::put('/profile/editOpinion/{opinion}', [OpinionController::class, 'editOpinion'])->middleware('auth')->name('editOpinion');
Route::delete('profile/deleteOpinion/{opinion}', [OpinionController::class, 'deleteOpinion'])->middleware('auth')->name('deleteOpinion');

//editing user profile
Route::get('/user/edit', [App\Http\Controllers\User\UserEditProfileController::class, 'index'])->name('userEdit');
Route::delete('/user/edit', [App\Http\Controllers\User\UserEditProfileController::class, 'destroy'])->name('userEdit');
Route::post('/user/edit', [UserEditProfileController::class, 'resetPswd'])->name('reset_pswd');

Route::get('/user/edit/description', [App\Http\Controllers\User\UserEditProfileController::class, 'showDescriptionBlade'])->name('showDescriptionBlade');
Route::post('/user/edit/description', [UserEditProfileController::class, 'storeAbout'])->name('addAbout');

Route::get('/user/edit/nickname', [App\Http\Controllers\User\UserEditProfileController::class, 'showNicknameBlade'])->name('showNicknameBlade');
Route::post('/user/edit/nickname', [UserEditProfileController::class, 'storeNickname'])->name('addNickname');

Route::get('/user/edit/accountType', [App\Http\Controllers\User\UserEditProfileController::class, 'showAccountTypeBlade'])->name('showAccountTypeBlade');
Route::post('/user/edit/accountType', [UserEditProfileController::class, 'storeAccountType'])->name('storeAccountType');

Route::get('/user/edit/photo', [App\Http\Controllers\User\UserEditProfileController::class, 'showPhotoBlade'])->name('showPhotoBlade');
Route::post('/user/edit/photo', [UserEditProfileController::class, 'storePhoto'])->name('storePhoto');

//Messages
Route::get('/profile/{user}/messages', [MessageController::class, 'index'])->middleware('auth')->name('messageList');
Route::post('/profile/{user}/messages', [MessageController::class, 'newMessage'])->middleware('auth')->name('newMessage');
Route::get('/messages/getuser/{id}', [MessageController::class, 'getUser'])->middleware('auth');
Route::post('/messages/markread/{id}', [MessageController::class, 'markRead'])->middleware('auth');
Route::get('/messages/badges', [MessageController::class, 'countBadges'])->middleware('auth');


//Administator
Route::prefix('admin')->name('admin.')->middleware('admin')->group(function (){
    Route::resource('/users', UserController::class);
    
});

Route::post('admin/users/{user}/block', [UserController::class, 'block'])->middleware('admin')->name('admin.users.block');
Route::put('admin/users/{user}/unblock', [UserController::class, 'unblock'])->middleware('admin')->name('admin.users.unblock');
Route::put('admin/users/{user}/makeadmin', [UserController::class, 'makeadmin'])->middleware('admin')->name('admin.users.makeadmin');

//Calendar
Route::get('/calendar', [App\Http\Controllers\UsersAdvertisementsController::class, 'index'])->middleware('auth')->name('calendar');
Route::get('/calendarsend', [App\Http\Controllers\UsersAdvertisementsController::class, 'send'])->middleware('auth')->name('calendarsend');
//Search
Route::get('/search', [App\Http\Controllers\SearchController::class, 'index'])->name('search');
//Availability
Route::prefix('availability')->name('availability.')->middleware('auth')->group(function (){
    Route::resource('/availability', AvailabilityController::class);
    
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
    
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{{asset('niania-logo.avif')}}" />

    <!-- Stars-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/stars.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
            <div class="container">
                <img src="{{ asset('images/niania-logo.avif') }}"  width="45" alt="" class="d-inline-block align-middle mr-2">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto w-auto">
                        <li class="nav-item mx-2">
                            <form class="form-inline" action="{{route('search')}}" method="GET">
                                <input type="text" class="form-control mr-1" id="search" name="search">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{{__("Wyszukaj")}}</button>
                            </form>
                        </li>
                        <!-- Authentication Links -->

                        @auth
                            <li class="nav-item mx-2">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-outline-secondary" id="userButton" name="userButton" onclick="window.location = '{{ route("dashboard") }}'">{{auth()->user()->nickname}}</button>
                                    <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="alert alert-info dropdown-item m-0" href="{{route('add_advert')}}">{{__('Dodaj ogłoszenie')}}</a>
                                        <a class="dropdown-item" href="{{route('show_advert')}}">{{__('Moje ogłoszenia')}}</a>
                                        <a class="dropdown-item" href="{{route('userOpinions', auth()->user())}}">{{__('Moje opinie')}}</a>
                                        <a class="dropdown-item" href="{{route('showApplications')}}" id="applications" name="applications">{{__('Zgłoszenia')}}</a>
                                        <div class="dropdown-divider"></div>                                        
                                        <a class="dropdown-item" href="{{route('messageList', auth()->user())}}" id="userMessages" name="userMessages">{{__('Wiadomości')}}</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{{ route('calendar') }}">{{__('Grafik')}}</a>
                                        <a class="dropdown-item" href="{{ route('availability.availability.index') }}">{{__('Dostępność')}}</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="alert alert-warning dropdown-item m-0 text-dark" href="{{ route('userEdit') }}">{{__('Edytuj konto')}}</a>
                                      </div>
                                </div>
                            </li>

                            @admin

                                <li class="nav-item mx-2">
                                    <a class=" btn btn-outline-danger font-weight-bold" href="{{ route('admin.users.index') }}">{{ __('Administrator') }}</a>
                                </li>

                            @endadmin


                            <li class="nav-item mx-2">
                                <form id="my_form" action="{{ route('logout') }}" method="POST">
                                    @csrf
                                    <button class="btn btn-outline-secondary font-weight-bold">{{ __('Wyloguj się') }}</button>

                                </form>
                            </li>

                        @endauth
                        
                        @guest

                            <li class="nav-item mx-2">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Logowanie') }}</a>
                            </li>

                        
                            <li class="nav-item mx-2">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Rejestracja') }}</a>
                            </li>

                        @endguest
                        
             
  
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 mb-4">
            @yield('content')
        </main>
        <footer class="py-3 bg-dark fixed-bottom">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Inz 2021</p>
            </div>
        </footer>
    </div>

    <script  src="{{asset('js/add_form.js')}}"></script>
    <script>
        $(document).ready(function()
        {
            var AuthUser = "{{{ (Auth::user()) ? Auth::user() : null }}}";

            if( AuthUser != null)
            {
                $.ajax({
                    url: '/messages/badges',
                    type: 'get',
                    dataType: 'json',
                    success: function(response){
                        if(Object.keys(response).length > 0)
                        {
                            let userButton = $('#userButton').html();
                            let userMessages = $('#userMessages').html();
                            let userApplications = $('#applications').html();
                            let countAll = response['messages'] + response['applications'];
                            
                            

                            if(countAll > 0)
                            {
                                let badgeMain = '<span class="badge badge-danger">'+ countAll +'</span>';
                                $('#userButton').html(userButton + ' ' + badgeMain);
                            }

                            if(response['messages'] > 0)
                            {
                                let badgeMessages = '<span class="badge badge-danger">'+ response['messages'] +'</span>';
                                $('#userMessages').html(userMessages + ' ' + badgeMessages);
                            }
                            
                            if(response['applications'] > 0)
                            {
                                let badgeApplications = '<span class="badge badge-danger">'+ response['applications'] +'</span>';
                                $('#applications').html(userApplications + ' ' + badgeApplications);
                            }
                        }                    
                    }
                });
            }            
        });
    </script>
</body>
</html>